export const GET_EMPLOYEES_LOADING = 'GET_EMPLOYEES_LOADING';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR';

export const DELETE_EMPLOYEES_LOADING = 'DELETE_EMPLOYEES_LOADING';
export const DELETE_EMPLOYEES_SUCCESS = 'DELETE_EMPLOYEES_SUCCESS';
export const DELETE_EMPLOYEES_ERROR = 'DELETE_EMPLOYEES_ERROR';

export const PUT_EMPLOYEES_LOADING = 'PUT_EMPLOYEES_LOADING';
export const PUT_EMPLOYEES_SUCCESS = 'PUT_EMPLOYEES_SUCCESS';
export const PUT_EMPLOYEES_ERROR = 'PUT_EMPLOYEES_ERROR';
export const SET_EMPLOYEE = 'SET_EMPLOYEE';

export const ADD_EMPLOYEES_LOADING = 'ADD_EMPLOYEES_LOADING';
export const ADD_EMPLOYEES_SUCCESS = 'ADD_EMPLOYEES_SUCCESS';
export const ADD_EMPLOYEES_ERROR = 'ADD_EMPLOYEES_ERROR';
