export const GET_EMPLOYEES_LOADING = 'GET_EMPLOYEES_LOADING';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR';

export const GET_EMPLOYEES_FILTERED_LOADING = 'GET_EMPLOYEES_FILTERED_LOADING';
export const GET_EMPLOYEES_FILTERED_SUCCESS = 'GET_EMPLOYEES_FILTERED_SUCCESS';
export const GET_EMPLOYEES_FILTERED_ERROR = 'GET_EMPLOYEES_FILTERED_ERROR';

export const DELETE_EMPLOYEE_LOADING = 'DELETE_EMPLOYEE_LOADING';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_ERROR = 'DELETE_EMPLOYEE_ERROR';

export const PUT_EMPLOYEE_LOADING = 'PUT_EMPLOYEE_LOADING';
export const PUT_EMPLOYEE_SUCCESS = 'PUT_EMPLOYEE_SUCCESS';
export const PUT_EMPLOYEE_ERROR = 'PUT_EMPLOYEE_ERROR';
export const SET_EMPLOYEE = 'SET_EMPLOYEE';

export const ADD_EMPLOYEE_LOADING = 'ADD_EMPLOYEE_LOADING';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_ERROR = 'ADD_EMPLOYEE_ERROR';

export const CLEAR_ERROR = 'CLEAR_ERROR';
