export const GET_TASKS_LOADING = 'GET_TASKS_LOADING';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_ERROR = 'GET_TASKS_ERROR';

export const DELETE_TASK_LOADING = 'DELETE_TASK_LOADING';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';

export const PUT_TASK_LOADING = 'PUT_TASK_LOADING';
export const PUT_TASK_SUCCESS = 'PUT_TASK_SUCCESS';
export const PUT_TASK_ERROR = 'PUT_TASK_ERROR';

export const ADD_TASK_LOADING = 'ADD_TASK_LOADING';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR';

export const SET_TASK = 'SET_TASK';

export const CLEAR_ERROR = 'CLEAR_ERROR';
