export const PUT_TIMESHEET_LOADING = 'PUT_TIMESHEET_LOADING';
export const PUT_TIMESHEET_SUCCESS = 'PUT_TIMESHEET_SUCCESS';
export const PUT_TIMESHEET_ERROR = 'PUT_TIMESHEET_ERROR';

export const ADD_TIMESHEET_LOADING = 'ADD_TIMESHEET_LOADING';
export const ADD_TIMESHEET_SUCCESS = 'ADD_TIMESHEET_SUCCESS';
export const ADD_TIMESHEET_ERROR = 'ADD_TIMESHEET_ERROR';

export const GET_TIMESHEETS_LOADING = 'GET_TIMESHEETS_LOADING';
export const GET_TIMESHEETS_SUCCESS = 'GETTIMESHEETS_SUCCESS';
export const GET_TIMESHEETS_ERROR = 'GET_TIMESHEETS_ERROR';

export const DELETE_TIMESHEET_LOADING = 'DELETE_TIMESHEET_LOADING';
export const DELETE_TIMESHEET_SUCCESS = 'DELETE_TIMESHEET_SUCCESS';
export const DELETE_TIMESHEET_ERROR = 'DELETE_TIMESHEET_ERROR';

export const SET_TIMESHEET = 'SET_TIMESHEET';

export const CLEAR_ERROR = 'CLEAR_ERROR';
