export const GET_SUPER_ADMINS_LOADING = 'GET_SUPER_ADMINS_LOADING';
export const GET_SUPER_ADMINS_SUCCESS = 'GET_SUPER_ADMINS_SUCCESS';
export const GET_SUPER_ADMINS_ERROR = 'GET_SUPER_ADMINS_ERROR';

export const DELETE_SUPER_ADMIN_LOADING = 'DELETE_SUPER_ADMIN_LOADING';
export const DELETE_SUPER_ADMIN_SUCCESS = 'DELETE_SUPER_ADMIN_SUCCESS';
export const DELETE_SUPER_ADMIN_ERROR = 'DELETE_SUPER_ADMIN_ERROR';

export const PUT_SUPER_ADMIN_LOADING = 'PUT_SUPER_ADMIN_LOADING';
export const PUT_SUPER_ADMIN_SUCCESS = 'PUT_SUPER_ADMIN_SUCCESS';
export const PUT_SUPER_ADMIN_ERROR = 'PUT_SUPER_ADMIN_ERROR';
export const SET_SUPER_ADMIN = 'SET_SUPER_ADMIN';

export const ADD_SUPER_ADMIN_LOADING = 'ADD_SUPER_ADMIN_LOADING';
export const ADD_SUPER_ADMIN_SUCCESS = 'ADD_SUPER_ADMIN_SUCCESS';
export const ADD_SUPER_ADMIN_ERROR = 'ADD_SUPER_ADMIN_ERROR';

export const CLEAR_ERROR = 'CLEAR_ERROR';
