export const GET_PROJECTS_LOADING = 'GET_PROJECTS_LOADING';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';

export const GET_PROJECTS_FILTERED_LOADING = 'GET_PROJECTS_FILTERED_LOADING';
export const GET_PROJECTS_FILTERED_SUCCESS = 'GET_PROJECTS_FILTERED_SUCCESS';
export const GET_PROJECTS_FILTERED_ERROR = 'GET_PROJECTS_FILTERED_ERROR';

export const DELETE_PROJECT_LOADING = 'DELETE_PROJECT_LOADING';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_ERROR = 'DELETE_PROJECT_ERROR';

export const PUT_PROJECT_LOADING = 'PUT_PROJECT_LOADING';
export const PUT_PROJECT_SUCCESS = 'PUT_PROJECT_SUCCESS';
export const PUT_PROJECT_ERROR = 'PUT_PROJECT_ERROR';

export const ADD_PROJECT_LOADING = 'ADD_PROJECT_LOADING';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_ERROR = 'ADD_PROJECT_ERROR';

export const SET_PROJECT = 'SET_PROJECT';
export const CLEAR_ERROR = 'CLEAR ERROR';
export const CLEAR_PROJECTS = 'CLEAR PROJECTS';
