export const GET_ADMINS_LOADING = 'GET_ADMINS_LOADING';
export const GET_ADMINS_SUCCESS = 'GET_ADMINS_SUCCESS';
export const GET_ADMINS_ERROR = 'GET_ADMINS_ERROR';

export const DELETE_ADMIN_LOADING = 'DELETE_ADMIN_LOADING';
export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS';
export const DELETE_ADMIN_ERROR = 'DELETE_ADMIN_ERROR';

export const PUT_ADMIN_LOADING = 'PUT_ADMIN_LOADING';
export const PUT_ADMIN_SUCCESS = 'PUT_ADMIN_SUCCESS';
export const PUT_ADMIN_ERROR = 'PUT_ADMIN_ERROR';
export const SET_ADMIN = 'SET_ADMIN';

export const ADD_ADMIN_LOADING = 'ADD_ADMIN_LOADING';
export const ADD_ADMIN_SUCCESS = 'ADD_ADMIN_SUCCESS';
export const ADD_ADMIN_ERROR = 'ADD_ADMIN_ERROR';

export const CLEAR_ERROR = 'CLEAR_ERROR';
