export const GET_ADMINS_LOADING = 'GET_ADMINS_LOADING';
export const GET_ADMINS_SUCCESS = 'GET_ADMINS_SUCCESS';
export const GET_ADMINS_ERROR = 'GET_ADMINS_ERROR';

export const DELETE_ADMINS_LOADING = 'DELETE_ADMINS_LOADING';
export const DELETE_ADMINS_SUCCESS = 'DELETE_ADMINS_SUCCESS';
export const DELETE_ADMINS_ERROR = 'DELETE_ADMINS_ERROR';

export const PUT_ADMINS_LOADING = 'PUT_ADMINS_LOADING';
export const PUT_ADMINS_SUCCESS = 'PUT_ADMINS_SUCCESS';
export const PUT_ADMINS_ERROR = 'PUT_ADMINS_ERROR';

export const ADD_ADMINS_LOADING = 'ADD_ADMINS_LOADING';
export const ADD_ADMINS_SUCCESS = 'ADD_ADMINS_SUCCESS';
export const ADD_ADMINS_ERROR = 'ADD_ADMINS_ERROR';
